{
 "title": "在线数量图表",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总览",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "在线数" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "query": "SELECT mean(\"DeviceChejiCount\") AS A, mean(\"ClientChejiCount\") FROM \"statistics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "DeviceChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "设备在线数" ], "type": "alias" }
      ],
      [
       { "params": [ "OcxChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "OCX在线数" ], "type": "alias" }
      ],
      [
       { "params": [ "WebSocketFmp4ChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "WebSocketFMP4在线数" ], "type": "alias" }
      ],
      [
       { "params": [ "WebSocketJT1078ChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "WebSocketJT1078在线数" ], "type": "alias" }
      ],
      [
       { "params": [ "RtmpChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "RTMP在线数" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "详细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "设备",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "设备在线数",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "query": "SELECT mean(\"ClientChejiCount\") FROM \"statistics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "DeviceChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WebsocketFMP4客户端",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "WebsocketFMP4客户端在线",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "WebSocketFmp4ChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WebSocketJT1078",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "WebSocketJT1078在线",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "WebSocketJT1078ChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OCX",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OCX在线数",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "query": "SELECT mean(\"ClientChejiCount\") FROM \"statistics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "OcxChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RTMP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RTMP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "statistics",
     "select": [
      [
       { "params": [ "RtmpChejiCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}